title: Aashutosh Joshi | AI Researcher
logo: /assets/img/headshot_circle.png
description: Portfolio of Aashutosh Joshi - AI, LLMs, and Complex Systems
show_downloads: false
theme: jekyll-theme-minimal
